### ISSUE TITLE
Unpin scipy

### ISSUE THREAD

**Issue by cthoyt** [gyorilab/indra_cogex#124]
We're currently pinning scipy in https://github.com/bgyori/indra_cogex/blob/7a0775e20e2f013d90592dc5372bdcb1a11ef104/setup.cfg#L47 because of an issue 1.8 had with hypergeometric CDF performance.

It appears that the linked issue https://github.com/scipy/scipy/issues/16079 has been solved. I also tested myself on the newest version and got results that didn't have the massive slowdown: https://github.com/scipy/scipy/issues/16079#issuecomment-1303289080

**Comment by bgyori** [comment]
The issue is unlikely to have been solved for the purposes of what we are doing here, if you read that thread more carefully.

**Comment by cthoyt** [comment]
So it's more of a platform-specific boost issue I can't reproduce?
