### ISSUE TITLE
Subnetwork curation issues

### ISSUE THREAD

**Issue by bgyori** [gyorilab/indra_cogex#160]
At https://discovery.indra.bio/curate/subnetwork:
- curation doesn't work even after logging in
- CURIEs have to use the INDRA standard (e.g., HGNC:6192, CHEBI:CHEBI:71200) which would normally be fine but it's a bit inconsistent since other parts of the website assume Bioregistry curies like chebi:71200
- When no statements are found, we get a message saying "There are no statements for this publication." which is not quite right since we aren't looking at publications

**Comment by kkaris** [comment]
> When no statements are found, we get a message saying "There are no statements for this publication." which is not quite right since we aren't looking at publications

Fixed by 0d3c4ec7f26cf2383dc8ff84fb280c2217a73792 and 86bfe2406057908c68988b7c0957f6709a55c18f

> CURIEs have to use the INDRA standard (e.g., HGNC:6192, CHEBI:CHEBI:71200) which would normally be fine but it's a bit inconsistent since other parts of the website assume Bioregistry curies like chebi:71200

Fixed by bdc99a34fafd9d026f6109b59045dfccdcd84263

See branch [`fixes`](https://github.com/gyorilab/indra_cogex/tree/fixes)

**Comment by kkaris** [comment]
> curation doesn't work even after logging in

This was probably an intermittent issue since curation seems to be working now
